name: ci

on: [push]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PHPUnit Tests
      uses: php-actions/phpunit@v1
      env:
          TEST_NAME: CalculadoraTest
      with:
          configuration: public/Tests/phpunit.xml
          args: --coverage-text
